import { lstat, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { TextDecoder } from "node:util";

import ts from "typescript";

export const MAX_CASES_FILE_BYTES = 65_536;
export const MAX_DETECTOR_SOURCE_BYTES = 131_072;
export const MAX_FIXTURE_BYTES = 1_048_576;

const KEBAB_CASE_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/u;
const DETECTOR_ID_PATTERN =
  /^[a-z0-9]+(?:-[a-z0-9]+)*\/[a-z0-9]+(?:-[a-z0-9]+)*$/u;
const FIXTURE_EXTENSIONS = new Set([".log", ".txt"]);
const FIXTURE_FILENAME_PATTERN = /^[a-z0-9]+(?:[._-][a-z0-9]+)*\.(?:log|txt)$/u;
const WINDOWS_RESERVED_FILENAME_PATTERN =
  /^(?:aux|com[1-9]|con|lpt[1-9]|nul|prn)(?:\.|$)/u;
const CASES_KEYS = new Set(["detectorId", "cases"]);
const CASE_KEYS = new Set(["name", "fixture", "expect"]);
const EXPECT_KEYS = new Set(["match", "score"]);
const GENERATED_HEADER = `// This file is generated by packages/registry/scripts/generate-registry-index.mjs.\n// DO NOT EDIT MANUALLY. Run "pnpm registry:generate" instead.\n`;

export class RegistryValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = "RegistryValidationError";
  }
}

export function compareAscii(left, right) {
  if (left < right) {
    return -1;
  }
  if (left > right) {
    return 1;
  }
  return 0;
}

function fail(context, message) {
  throw new RegistryValidationError(`${context}: ${message}`);
}

function isPlainObject(value) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

function assertPlainObject(value, context) {
  if (!isPlainObject(value)) {
    fail(context, "must be a plain object");
  }
}

function assertOnlyKeys(value, allowed, context) {
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      fail(context, `field "${key}" is not supported`);
    }
  }
}

function assertNonEmptyString(value, context) {
  if (typeof value !== "string" || value.trim().length === 0) {
    fail(context, "must be a non-empty string");
  }
}

function assertKebabName(value, context) {
  if (!KEBAB_CASE_PATTERN.test(value)) {
    fail(context, "must use lowercase kebab-case");
  }
}

function assertScore(value, context) {
  if (!Number.isInteger(value) || value < 1 || value > 100) {
    fail(context, "must be an integer between 1 and 100");
  }
}

function assertFixtureFilename(value, context) {
  if (
    !FIXTURE_FILENAME_PATTERN.test(value) ||
    WINDOWS_RESERVED_FILENAME_PATTERN.test(value)
  ) {
    fail(
      context,
      "must use a portable lowercase file name ending in .log or .txt",
    );
  }
}

function isStaticPropertyName(name) {
  return ts.isIdentifier(name) || ts.isStringLiteral(name);
}

function isDataOnlyExpression(expression) {
  if (
    ts.isStringLiteral(expression) ||
    ts.isNumericLiteral(expression) ||
    expression.kind === ts.SyntaxKind.TrueKeyword ||
    expression.kind === ts.SyntaxKind.FalseKeyword ||
    expression.kind === ts.SyntaxKind.NullKeyword
  ) {
    return true;
  }
  if (ts.isParenthesizedExpression(expression)) {
    return isDataOnlyExpression(expression.expression);
  }
  if (ts.isPrefixUnaryExpression(expression)) {
    return (
      (expression.operator === ts.SyntaxKind.MinusToken ||
        expression.operator === ts.SyntaxKind.PlusToken) &&
      ts.isNumericLiteral(expression.operand)
    );
  }
  if (ts.isArrayLiteralExpression(expression)) {
    return expression.elements.every(
      (element) =>
        !ts.isOmittedExpression(element) && isDataOnlyExpression(element),
    );
  }
  if (ts.isObjectLiteralExpression(expression)) {
    return expression.properties.every(
      (property) =>
        ts.isPropertyAssignment(property) &&
        isStaticPropertyName(property.name) &&
        isDataOnlyExpression(property.initializer),
    );
  }
  return false;
}

export function validateDetectorModuleSource(source, context = "detector.ts") {
  const sourceFile = ts.createSourceFile(
    "detector.ts",
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const [syntaxError] = sourceFile.parseDiagnostics;
  if (syntaxError !== undefined) {
    fail(
      context,
      `contains invalid TypeScript: ${ts.flattenDiagnosticMessageText(syntaxError.messageText, " ")}`,
    );
  }

  const imports = sourceFile.statements.filter(ts.isImportDeclaration);
  const exports = sourceFile.statements.filter(ts.isExportAssignment);
  if (
    sourceFile.statements.length !== 2 ||
    imports.length !== 1 ||
    exports.length !== 1
  ) {
    fail(
      context,
      "must contain exactly one defineDetector import and one default detector export",
    );
  }

  const [importDeclaration] = imports;
  const importClause = importDeclaration.importClause;
  const namedBindings = importClause?.namedBindings;
  const importElements =
    namedBindings !== undefined && ts.isNamedImports(namedBindings)
      ? namedBindings.elements
      : [];
  const [importElement] = importElements;
  if (
    !ts.isStringLiteral(importDeclaration.moduleSpecifier) ||
    importDeclaration.moduleSpecifier.text !== "@oss-error-registry/core" ||
    importClause === undefined ||
    importClause.isTypeOnly ||
    importClause.name !== undefined ||
    importElements.length !== 1 ||
    importElement?.propertyName !== undefined ||
    importElement?.name.text !== "defineDetector"
  ) {
    fail(
      context,
      'must import only { defineDetector } from "@oss-error-registry/core"',
    );
  }

  const [exportAssignment] = exports;
  const expression = exportAssignment.expression;
  if (
    exportAssignment.isExportEquals ||
    !ts.isCallExpression(expression) ||
    !ts.isIdentifier(expression.expression) ||
    expression.expression.text !== "defineDetector" ||
    expression.arguments.length !== 1 ||
    !ts.isObjectLiteralExpression(expression.arguments[0])
  ) {
    fail(context, "default export must call defineDetector with one object");
  }
  if (!isDataOnlyExpression(expression.arguments[0])) {
    fail(
      context,
      "detector definition must be a data-only object literal without callbacks, spreads, computed properties, or executable expressions",
    );
  }
}

export function validateFixturePath(fixture, expectedMatch, context) {
  assertNonEmptyString(fixture, `${context}.fixture`);
  if (fixture.includes("\\")) {
    fail(
      `${context}.fixture`,
      "must use forward slashes and remain inside the detector directory",
    );
  }
  if (path.posix.isAbsolute(fixture) || path.win32.isAbsolute(fixture)) {
    fail(`${context}.fixture`, "must be a relative path");
  }

  const segments = fixture.split("/");
  if (
    segments.some(
      (segment) => segment === "" || segment === "." || segment === "..",
    )
  ) {
    fail(
      `${context}.fixture`,
      "must not contain empty, current, or parent path segments",
    );
  }

  const expectedDirectory = expectedMatch ? "positive" : "negative";
  if (
    segments[0] !== "fixtures" ||
    segments[1] !== expectedDirectory ||
    segments.length !== 3
  ) {
    fail(
      `${context}.fixture`,
      `must use "fixtures/${expectedDirectory}/<file>.log" or a .txt file`,
    );
  }
  if (!FIXTURE_EXTENSIONS.has(path.posix.extname(fixture))) {
    fail(`${context}.fixture`, "must use a .log or .txt file extension");
  }
  assertFixtureFilename(segments[2], `${context}.fixture`);

  return fixture;
}

export function validateCasesDocument(value, options = {}) {
  const fileLabel = options.fileLabel ?? "cases.json";
  assertPlainObject(value, fileLabel);
  assertOnlyKeys(value, CASES_KEYS, fileLabel);
  assertNonEmptyString(value.detectorId, `${fileLabel}.detectorId`);
  if (!DETECTOR_ID_PATTERN.test(value.detectorId)) {
    fail(
      `${fileLabel}.detectorId`,
      'must use lowercase kebab-case in the form "<ecosystem>/<detector-name>"',
    );
  }
  if (
    options.expectedDetectorId !== undefined &&
    value.detectorId !== options.expectedDetectorId
  ) {
    fail(
      `${fileLabel}.detectorId`,
      `must equal detector directory ID "${options.expectedDetectorId}"`,
    );
  }
  if (!Array.isArray(value.cases) || value.cases.length === 0) {
    fail(`${fileLabel}.cases`, "must be a non-empty array");
  }

  const caseNames = new Set();
  const fixturePaths = new Set();
  const cases = value.cases.map((caseValue, index) => {
    const caseContext = `${fileLabel}.cases[${index}]`;
    assertPlainObject(caseValue, caseContext);
    assertOnlyKeys(caseValue, CASE_KEYS, caseContext);
    assertNonEmptyString(caseValue.name, `${caseContext}.name`);
    if (caseNames.has(caseValue.name)) {
      fail(`${caseContext}.name`, `duplicates case name "${caseValue.name}"`);
    }
    caseNames.add(caseValue.name);

    assertPlainObject(caseValue.expect, `${caseContext}.expect`);
    assertOnlyKeys(caseValue.expect, EXPECT_KEYS, `${caseContext}.expect`);
    if (typeof caseValue.expect.match !== "boolean") {
      fail(`${caseContext}.expect.match`, "must be a boolean");
    }
    if (caseValue.expect.match) {
      if (!Object.hasOwn(caseValue.expect, "score")) {
        fail(`${caseContext}.expect.score`, "is required when match is true");
      }
      assertScore(caseValue.expect.score, `${caseContext}.expect.score`);
    } else if (Object.hasOwn(caseValue.expect, "score")) {
      fail(
        `${caseContext}.expect.score`,
        "must be omitted when match is false",
      );
    }

    const fixture = validateFixturePath(
      caseValue.fixture,
      caseValue.expect.match,
      caseContext,
    );
    if (fixturePaths.has(fixture)) {
      fail(
        `${caseContext}.fixture`,
        `duplicates fixture reference "${fixture}"`,
      );
    }
    fixturePaths.add(fixture);

    return Object.freeze({
      name: caseValue.name,
      fixture,
      expect: Object.freeze(
        caseValue.expect.match
          ? { match: true, score: caseValue.expect.score }
          : { match: false },
      ),
    });
  });

  if (!cases.some(({ expect }) => expect.match)) {
    fail(`${fileLabel}.cases`, "must include at least one positive case");
  }
  if (!cases.some(({ expect }) => !expect.match)) {
    fail(`${fileLabel}.cases`, "must include at least one negative case");
  }

  return Object.freeze({
    detectorId: value.detectorId,
    cases: Object.freeze(cases),
  });
}

async function assertPathKind(targetPath, kind, context) {
  let stats;
  try {
    stats = await lstat(targetPath);
  } catch (error) {
    if (
      error !== null &&
      typeof error === "object" &&
      error.code === "ENOENT"
    ) {
      fail(context, `required ${kind} is missing`);
    }
    throw error;
  }
  if (stats.isSymbolicLink()) {
    fail(context, "symbolic links are not allowed");
  }
  if (kind === "file" ? !stats.isFile() : !stats.isDirectory()) {
    fail(context, `must be a ${kind}`);
  }
  return stats;
}

async function assertOnlyDirectoryEntries(directory, allowed, context) {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    if (!allowed.has(entry.name)) {
      fail(context, `unexpected entry "${entry.name}"`);
    }
  }
}

async function validateDetectorDirectory(entry) {
  const context = `Detector ${entry.detectorId}`;
  await assertOnlyDirectoryEntries(
    entry.directory,
    new Set(["detector.ts", "cases.json", "fixtures"]),
    context,
  );
  const detectorContext = `${context} detector.ts`;
  const detectorSource = await readBoundedUtf8File(
    path.join(entry.directory, "detector.ts"),
    MAX_DETECTOR_SOURCE_BYTES,
    detectorContext,
  );
  validateDetectorModuleSource(detectorSource, detectorContext);
  await assertPathKind(
    path.join(entry.directory, "cases.json"),
    "file",
    `${context} cases.json`,
  );
  const fixturesDirectory = path.join(entry.directory, "fixtures");
  await assertPathKind(fixturesDirectory, "directory", `${context} fixtures`);
  await assertOnlyDirectoryEntries(
    fixturesDirectory,
    new Set(["positive", "negative"]),
    `${context} fixtures`,
  );
  await assertPathKind(
    path.join(fixturesDirectory, "positive"),
    "directory",
    `${context} fixtures/positive`,
  );
  await assertPathKind(
    path.join(fixturesDirectory, "negative"),
    "directory",
    `${context} fixtures/negative`,
  );
}

export async function discoverDetectorDirectories(detectorsRoot) {
  await assertPathKind(detectorsRoot, "directory", "Registry detectors root");
  const ecosystemEntries = await readdir(detectorsRoot, {
    withFileTypes: true,
  });
  const detectors = [];

  for (const ecosystemEntry of ecosystemEntries) {
    const ecosystem = ecosystemEntry.name;
    if (!ecosystemEntry.isDirectory() || ecosystemEntry.isSymbolicLink()) {
      fail(`Ecosystem directory "${ecosystem}"`, "must be a real directory");
    }
    assertKebabName(ecosystem, `Ecosystem directory "${ecosystem}"`);

    const ecosystemDirectory = path.join(detectorsRoot, ecosystem);
    const detectorEntries = await readdir(ecosystemDirectory, {
      withFileTypes: true,
    });
    for (const detectorEntry of detectorEntries) {
      const detectorName = detectorEntry.name;
      if (!detectorEntry.isDirectory() || detectorEntry.isSymbolicLink()) {
        fail(
          `Detector directory "${ecosystem}/${detectorName}"`,
          "must be a real directory",
        );
      }
      assertKebabName(
        detectorName,
        `Detector directory "${ecosystem}/${detectorName}"`,
      );

      const detectorId = `${ecosystem}/${detectorName}`;
      const entry = Object.freeze({
        ecosystem,
        detectorName,
        detectorId,
        directory: path.join(ecosystemDirectory, detectorName),
      });
      await validateDetectorDirectory(entry);
      detectors.push(entry);
    }
  }

  detectors.sort((left, right) =>
    compareAscii(left.detectorId, right.detectorId),
  );
  return Object.freeze(detectors);
}

async function readBoundedUtf8File(filePath, maximumBytes, context) {
  const stats = await assertPathKind(filePath, "file", context);
  if (stats.size > maximumBytes) {
    fail(context, `must not exceed ${maximumBytes} bytes`);
  }
  const buffer = await readFile(filePath);
  if (buffer.byteLength > maximumBytes) {
    fail(context, `must not exceed ${maximumBytes} bytes`);
  }
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(buffer);
  } catch {
    fail(context, "must contain valid UTF-8 text");
  }
}

async function readFixture(entry, caseDefinition) {
  const context = `Detector ${entry.detectorId}, case "${caseDefinition.name}", fixture "${caseDefinition.fixture}"`;
  const segments = caseDefinition.fixture.split("/");
  const fixturePath = path.resolve(entry.directory, ...segments);
  const relative = path.relative(entry.directory, fixturePath);
  if (
    relative === ".." ||
    relative.startsWith(`..${path.sep}`) ||
    path.isAbsolute(relative)
  ) {
    fail(context, "path escapes the detector directory");
  }

  let current = entry.directory;
  for (const [index, segment] of segments.entries()) {
    current = path.join(current, segment);
    const kind = index === segments.length - 1 ? "file" : "directory";
    await assertPathKind(current, kind, context);
  }

  const fixtureText = await readBoundedUtf8File(
    fixturePath,
    MAX_FIXTURE_BYTES,
    context,
  );
  if (fixtureText.trim().length === 0) {
    fail(context, "must contain non-whitespace text");
  }
  return fixtureText;
}

async function listFixtureFiles(entry) {
  const files = [];
  for (const kind of ["positive", "negative"]) {
    const directory = path.join(entry.directory, "fixtures", kind);
    const entries = await readdir(directory, { withFileTypes: true });
    for (const fileEntry of entries) {
      const relativePath = `fixtures/${kind}/${fileEntry.name}`;
      if (!fileEntry.isFile() || fileEntry.isSymbolicLink()) {
        fail(
          `Detector ${entry.detectorId}, fixture "${relativePath}"`,
          "must be a regular file",
        );
      }
      if (!FIXTURE_EXTENSIONS.has(path.posix.extname(fileEntry.name))) {
        fail(
          `Detector ${entry.detectorId}, fixture "${relativePath}"`,
          "must use a .log or .txt file extension",
        );
      }
      assertFixtureFilename(
        fileEntry.name,
        `Detector ${entry.detectorId}, fixture "${relativePath}"`,
      );
      files.push(relativePath);
    }
  }
  return files.sort(compareAscii);
}

async function loadDetectorCases(entry) {
  const casesPath = path.join(entry.directory, "cases.json");
  const fileLabel = `${entry.detectorId}/cases.json`;
  const source = await readBoundedUtf8File(
    casesPath,
    MAX_CASES_FILE_BYTES,
    fileLabel,
  );
  let parsed;
  try {
    parsed = JSON.parse(source);
  } catch {
    fail(fileLabel, "must contain valid JSON");
  }

  const document = validateCasesDocument(parsed, {
    expectedDetectorId: entry.detectorId,
    fileLabel,
  });
  const referencedFixtures = new Set(
    document.cases.map(({ fixture }) => fixture),
  );
  const fixtureFiles = await listFixtureFiles(entry);
  for (const fixture of fixtureFiles) {
    if (!referencedFixtures.has(fixture)) {
      fail(
        `Detector ${entry.detectorId}, fixture "${fixture}"`,
        "is not referenced by cases.json",
      );
    }
  }

  const cases = [];
  for (const caseDefinition of document.cases) {
    cases.push(
      Object.freeze({
        ...caseDefinition,
        fixtureText: await readFixture(entry, caseDefinition),
      }),
    );
  }
  return Object.freeze(cases);
}

export async function validateRegistryFilesystem(detectorsRoot) {
  const entries = await discoverDetectorDirectories(detectorsRoot);
  const detectorIds = new Set();
  const validated = [];

  for (const entry of entries) {
    if (detectorIds.has(entry.detectorId)) {
      fail("Registry", `duplicate detector ID "${entry.detectorId}"`);
    }
    detectorIds.add(entry.detectorId);
    validated.push(
      Object.freeze({ ...entry, cases: await loadDetectorCases(entry) }),
    );
  }

  return Object.freeze(validated);
}

export function validateLoadedDetectorCollection(entries, detectors) {
  if (!Array.isArray(detectors)) {
    fail("Loaded registry", "detectors must be an array");
  }
  if (detectors.length !== entries.length) {
    fail(
      "Loaded registry",
      `generated index contains ${detectors.length} detectors but ${entries.length} detector directories were discovered`,
    );
  }

  const detectorIds = new Map();
  for (let index = 0; index < entries.length; index += 1) {
    const entry = entries[index];
    const detector = detectors[index];
    const context = `Detector ${entry.detectorId} detector.ts`;
    if (detector === null || typeof detector !== "object") {
      fail(context, "default export must be a DetectorDefinition object");
    }
    if (typeof detector.id !== "string") {
      fail(context, "default export must have a string detector ID");
    }
    const firstDirectoryId = detectorIds.get(detector.id);
    if (firstDirectoryId !== undefined) {
      fail(
        context,
        `duplicates loaded detector ID "${detector.id}" first loaded for directory "${firstDirectoryId}"`,
      );
    }
    detectorIds.set(detector.id, entry.detectorId);
    if (detector.id !== entry.detectorId) {
      fail(
        context,
        `default export ID "${detector.id}" must equal directory ID "${entry.detectorId}"`,
      );
    }
    if (detector.ecosystem !== entry.ecosystem) {
      fail(
        context,
        `ecosystem "${String(detector.ecosystem)}" must equal directory ecosystem "${entry.ecosystem}"`,
      );
    }
  }
}

function detectorIdentifier(detectorId) {
  return `detector_${detectorId.replace("/", "__").replaceAll("-", "_")}`;
}

export function renderRegistryIndex(entries) {
  const sorted = [...entries].sort((left, right) =>
    compareAscii(left.detectorId, right.detectorId),
  );
  const detectorIds = new Set();
  for (const entry of sorted) {
    if (detectorIds.has(entry.detectorId)) {
      fail("Registry generator", `duplicate detector ID "${entry.detectorId}"`);
    }
    detectorIds.add(entry.detectorId);
  }

  const imports = sorted
    .map(
      (entry) =>
        `import ${detectorIdentifier(entry.detectorId)} from "../detectors/${entry.ecosystem}/${entry.detectorName}/detector.js";`,
    )
    .join("\n");
  const identifiers = sorted
    .map((entry) => `  ${detectorIdentifier(entry.detectorId)},`)
    .join("\n");

  return `${GENERATED_HEADER}\nimport type { DetectorDefinition } from "@oss-error-registry/core";\n${imports.length > 0 ? `\n${imports}\n` : ""}\nexport const builtInDetectors: readonly DetectorDefinition[] = Object.freeze([\n${identifiers}${identifiers.length > 0 ? "\n" : ""}]);\n`;
}

export async function generateRegistryIndex(options) {
  const entries = await validateRegistryFilesystem(options.detectorsRoot);
  const output = renderRegistryIndex(entries);
  let current = "";
  try {
    current = await readFile(options.generatedFile, "utf8");
  } catch (error) {
    if (
      error === null ||
      typeof error !== "object" ||
      error.code !== "ENOENT"
    ) {
      throw error;
    }
  }

  const changed = current !== output;
  if (options.check) {
    if (changed) {
      fail(
        "Generated registry index",
        'is out of date; run "pnpm registry:generate"',
      );
    }
  } else if (changed) {
    await mkdir(path.dirname(options.generatedFile), { recursive: true });
    await writeFile(options.generatedFile, output, "utf8");
  }

  return Object.freeze({ changed, entries, output });
}
